 # Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # Using IP for nfs to fix slow unmounting on shutdown.
  # "noauto" "x-systemd.automount"
  fileSystems."/mnt/data" = {
    device = "100.96.28.102:/mnt/main/data";
    fsType = "nfs";
    options = [ "noauto" "x-systemd.automount" "x-systemd.mount-timeout=60" "hard" "rw" "async" "nfsvers=4.2" "_netdev" "x-systemd.requires=tailscaled.service" ];
  };

  fileSystems."/mnt/games" = {
    device = "100.96.28.102:/mnt/main/games";
    fsType = "nfs";
    options = [ "noauto" "x-systemd.automount" "x-systemd.mount-timeout=60" "hard" "rw" "async" "nfsvers=4.2" "_netdev" "x-systemd.requires=tailscaled.service" ];
  };


  networking.useDHCP = lib.mkDefault true;

  # sudo install -dm700 /var/lib/bluetooth
  hardware.bluetooth.enable = true; # enables support for Bluetooth
  hardware.bluetooth.powerOnBoot = true; # powers up the default Bluetooth controller on boot
  hardware.bluetooth.settings = {
    General = {
      Enable = "Source,Sink,Media,Socket";
    };
  };
  hardware.bluetooth.input = {
    General = { UserspaceHID = true; };
  };
  boot.extraModprobeConfig = '' options bluetooth disable_ertm=1 '';

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

