 # Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "mem_sleep_default=deep" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a69ac279-9514-42da-b6a5-ab0e2a5be95a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6B7D-9DA3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Using IP for nfs to fix slow unmounting on shutdown.
  # "noauto" "x-systemd.automount"
  fileSystems."/mnt/data" = {
    device = "100.96.28.102:/mnt/main/data";
    fsType = "nfs";
    options = [ "noauto" "x-systemd.automount" "x-systemd.mount-timeout=20" "hard" "rw" "async" "nfsvers=4.2" "_netdev" "x-systemd.requires=tailscaled.service" ];
  };

  fileSystems."/mnt/games/PrismLauncher" = {
    device = "100.96.28.102:/mnt/main/games/PrismLauncher";
    fsType = "nfs";
    options = [ "noauto" "x-systemd.automount" "x-systemd.mount-timeout=20" "hard" "rw" "async" "nfsvers=4.2" "_netdev" "x-systemd.requires=tailscaled.service" ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6a94bde0-3b03-4230-8115-b93003aa6a80"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  # sudo install -dm700 /var/lib/bluetooth
  hardware.bluetooth.enable = true; # enables support for Bluetooth
  hardware.bluetooth.powerOnBoot = true; # powers up the default Bluetooth controller on boot
  hardware.bluetooth.settings = {
    General = {
      Enable = "Source,Sink,Media,Socket";
    };
  };
  hardware.bluetooth.input = {
    General = { UserspaceHID = true; };
  };
  boot.extraModprobeConfig = '' options bluetooth disable_ertm=1 '';

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
